// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4uZ65LqcwbGSuXGSJzC_5tc8z5-gJAVw',
    appId: '1:1041183798130:web:442f367bf8833777f563eb',
    messagingSenderId: '1041183798130',
    projectId: 'movieapp-9b907',
    authDomain: 'movieapp-9b907.firebaseapp.com',
    storageBucket: 'movieapp-9b907.firebasestorage.app',
    measurementId: 'G-9438W95GSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDntLIkw7HJ9TrwFCKs1yy1t34_iVSHMWQ',
    appId: '1:1041183798130:android:1dd0a1442dd99ad4f563eb',
    messagingSenderId: '1041183798130',
    projectId: 'movieapp-9b907',
    storageBucket: 'movieapp-9b907.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqx2bwGyqokSII8wLgnGL1eoXNK-FXWHM',
    appId: '1:1041183798130:ios:9f8671cd89d776f9f563eb',
    messagingSenderId: '1041183798130',
    projectId: 'movieapp-9b907',
    storageBucket: 'movieapp-9b907.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqx2bwGyqokSII8wLgnGL1eoXNK-FXWHM',
    appId: '1:1041183798130:ios:9f8671cd89d776f9f563eb',
    messagingSenderId: '1041183798130',
    projectId: 'movieapp-9b907',
    storageBucket: 'movieapp-9b907.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4uZ65LqcwbGSuXGSJzC_5tc8z5-gJAVw',
    appId: '1:1041183798130:web:fa6c1f86627957c7f563eb',
    messagingSenderId: '1041183798130',
    projectId: 'movieapp-9b907',
    authDomain: 'movieapp-9b907.firebaseapp.com',
    storageBucket: 'movieapp-9b907.firebasestorage.app',
    measurementId: 'G-SPYSNEHE3N',
  );
}
